version: "3.9"

services:
  nano_siem:
    build:
      context: .
      dockerfile: Dockerfile
    # user: 1000:1000
    environment:
      - MYSQL_DB_NAME=NanoSiem
      - MYSQL_USER=NanoSiem
      - MYSQL_PASSWORD=wLzLQHR8tni5VKdar4dVPkAR3CIv0l
      - MYSQL_HOST=nano_siem_db
      - TRAEFIK_SERVICE_NAME=Traefik
    ports:
      - 127.0.0.1:8000:8000
    volumes:
      - $PWD/../nano_siem_data/access.log.backup.3:/var/log/access.log
  nano_siem_db:
    image: mariadb:10.10
    user: 1000:1000
    volumes:
      - $PWD/../nano_siem_data/database:/var/lib/mysql
    environment:
      - MARIADB_USER=NanoSiem
      - MARIADB_DATABASE=NanoSiem
      - MARIADB_PASSWORD=wLzLQHR8tni5VKdar4dVPkAR3CIv0l
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
    ports:
      - 127.0.0.1:3306:3306
