version: "3.9"

services:
  nano_siem:
    build:
      context: .
      dockerfile: Dockerfile
    # user: 1000:1000
    environment:
      - MYSQL_DB_NAME=NanoSiem
      - MYSQL_USER=NanoSiem
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=nano_siem_db
      - PRIVATE_IP_LOCATION_INFO=${PRIVATE_IP_LOCATION_INFO}
      - PLUGINS_LOG_LEVEL=DEBUG
    ports:
      - 127.0.0.1:8000:8000
    volumes:
      - $PWD/../nano_siem_data/access.log:/var/log/traefik_access.log
      - $PWD/../nano_siem_data/GeoIP.conf:/etc/GeoIP.conf
      - $PWD/crontab.log:/home/NanoSiem/.nano_siem/crontab.log

  nano_siem_db:
    image: mariadb:10.10
    user: 1000:1000
    volumes:
      - $PWD/../nano_siem_data/database:/var/lib/mysql
    command: --innodb-buffer-pool-size=5G --key-buffer-size=1G
    environment:
      - MARIADB_USER=NanoSiem
      - MARIADB_DATABASE=NanoSiem
      - MARIADB_PASSWORD=wLzLQHR8tni5VKdar4dVPkAR3CIv0l
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
    ports:
      - 127.0.0.1:3306:3306
